added func to concat arbitrary num of strs, fixed heredoc using old command parse func. for some reason gnl reads '\n' instead of second input from stdin

diff --git a/test_script b/test_script
--- a/test_script
+++ b/test_script
@@ -1,3 +1,4 @@
 #!/bin/sh
 
 echo "lorem_ipsum"
+ >&2 echo "error_ipsum"
